/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Modelo.Conexion;
import com.mysql.jdbc.Connection;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.image.BufferedImage;
import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.IOException;
import java.io.InputStream;
import java.sql.Blob;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.time.LocalDate;
import java.time.Period;
import java.time.format.DateTimeFormatter;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author INFORMATICA-05
 */
public class AlumnosV extends javax.swing.JInternalFrame {
public DefaultTableModel modelt;
    /**
     * Creates new form AlumnosV
     */
    public AlumnosV() {
        initComponents();
        modelo();
    }
    
    public void modelo(){
        modelt = new DefaultTableModel();
        tblposgrado.setModel(modelt);
        
        modelt.addColumn("1");
        modelt.addColumn("2");
        modelt.addColumn("3");
        modelt.addColumn("4");
        modelt.addColumn("5");
        modelt.addColumn("6");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel25 = new javax.swing.JLabel();
        Porcentaje = new javax.swing.ButtonGroup();
        titlic = new javax.swing.ButtonGroup();
        conluyodip = new javax.swing.ButtonGroup();
        tituladodip = new javax.swing.ButtonGroup();
        conluyomae = new javax.swing.ButtonGroup();
        tituladomae = new javax.swing.ButtonGroup();
        concluyodoc = new javax.swing.ButtonGroup();
        tituladodoc = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        rbpormix = new javax.swing.JRadioButton();
        rbporpro = new javax.swing.JRadioButton();
        rbporper = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtmatricula = new javax.swing.JTextField();
        txtnombre = new javax.swing.JTextField();
        txtappat = new javax.swing.JTextField();
        txtapmat = new javax.swing.JTextField();
        txtcurp = new javax.swing.JTextField();
        txtfecnac = new javax.swing.JTextField();
        txtedad = new javax.swing.JTextField();
        txtfijo = new javax.swing.JTextField();
        txtcel = new javax.swing.JTextField();
        txtemail = new javax.swing.JTextField();
        txtestciv = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtporper = new javax.swing.JTextField();
        txtporpro = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        lblfoto = new javax.swing.JLabel();
        cmbsexo = new javax.swing.JComboBox<>();
        cmbpro = new javax.swing.JComboBox<>();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        txtid = new javax.swing.JTextField();
        btnfoto = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        txtcalle = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtnum = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        txtcol = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        txtcp = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        txtmun = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        txtest = new javax.swing.JTextField();
        jLabel42 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel46 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jCheckBox5 = new javax.swing.JCheckBox();
        jCheckBox6 = new javax.swing.JCheckBox();
        jCheckBox7 = new javax.swing.JCheckBox();
        jCheckBox8 = new javax.swing.JCheckBox();
        jLabel47 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtobs = new javax.swing.JTextPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        txtnomuni = new javax.swing.JTextField();
        txtuniciu = new javax.swing.JTextField();
        txtuniest = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        txtlic = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        rblicsi = new javax.swing.JRadioButton();
        rblicno = new javax.swing.JRadioButton();
        jLabel32 = new javax.swing.JLabel();
        txtotro = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel52 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel33 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel45 = new javax.swing.JLabel();
        txtpos = new javax.swing.JTextField();
        txtposuni = new javax.swing.JTextField();
        rbpossi = new javax.swing.JRadioButton();
        rbposno = new javax.swing.JRadioButton();
        rbtitsi = new javax.swing.JRadioButton();
        rbtitno = new javax.swing.JRadioButton();
        jLabel49 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        cmbpos = new javax.swing.JComboBox<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblposgrado = new javax.swing.JTable();
        btnagregar = new javax.swing.JButton();
        btnel = new javax.swing.JButton();
        btned = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel24 = new javax.swing.JLabel();
        txtbuscaralu = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblalumnos = new javax.swing.JTable();
        btnnuevo = new javax.swing.JButton();
        btnguardar = new javax.swing.JButton();
        btncancelar = new javax.swing.JButton();
        btneditar = new javax.swing.JButton();
        btneliminar = new javax.swing.JButton();
        btnsalir = new javax.swing.JButton();

        jLabel25.setText("jLabel25");

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Porcentaje.add(rbpormix);
        rbpormix.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        rbpormix.setText("Mixto");
        jPanel1.add(rbpormix, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 330, -1, -1));

        Porcentaje.add(rbporpro);
        rbporpro.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        rbporpro.setText("Procedencia");
        jPanel1.add(rbporpro, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 330, -1, -1));

        Porcentaje.add(rbporper);
        rbporper.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        rbporper.setText("Personal");
        jPanel1.add(rbporper, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 330, -1, -1));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setText("Matrícula");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setText("Nombre (s)");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setText("Apellido Paterno");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setText("Apellido Materno");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        jLabel6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel6.setText("CURP");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, -1, -1));

        jLabel7.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel7.setText("Fecha de Nac.");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 180, -1, -1));

        jLabel8.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel8.setText("Edad");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, -1, -1));

        jLabel9.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel9.setText("Sexo");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 210, -1, -1));

        jLabel10.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel10.setText("Teléfono Fijo");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, -1, -1));

        jLabel11.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel11.setText("Celular");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 240, -1, -1));

        jLabel12.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel12.setText("E-mail");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, -1, -1));

        jLabel13.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel13.setText("Estado Civil");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));

        jLabel14.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel14.setText("Procedencia");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, -1, -1));
        jPanel1.add(txtmatricula, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, 140, -1));
        jPanel1.add(txtnombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, 140, -1));
        jPanel1.add(txtappat, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, 140, -1));
        jPanel1.add(txtapmat, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, 140, -1));

        txtcurp.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtcurpFocusLost(evt);
            }
        });
        jPanel1.add(txtcurp, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, 140, -1));
        jPanel1.add(txtfecnac, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 180, 140, -1));
        jPanel1.add(txtedad, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 210, 140, -1));
        jPanel1.add(txtfijo, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 240, 140, -1));
        jPanel1.add(txtcel, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 240, 140, -1));
        jPanel1.add(txtemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 270, 410, -1));
        jPanel1.add(txtestciv, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, 140, -1));

        jLabel15.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel15.setText("Porcentaje de Pago");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, -1, 20));
        jPanel1.add(txtporper, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 390, 60, -1));
        jPanel1.add(txtporpro, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 360, 60, -1));

        jLabel16.setText("Procedencia");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 360, -1, -1));

        jLabel17.setText("Personal");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 390, -1, -1));

        lblfoto.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblfoto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblfoto.setText("FOTO");
        lblfoto.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lblfoto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblfotoMouseClicked(evt);
            }
        });
        jPanel1.add(lblfoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 20, 100, 120));

        cmbsexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hombre", "Mujer", "---" }));
        cmbsexo.setSelectedIndex(2);
        jPanel1.add(cmbsexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 210, 140, -1));

        cmbpro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "cvb" }));
        jPanel1.add(cmbpro, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 300, 410, -1));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 550, 10));

        jLabel50.setText("%");
        jPanel1.add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 390, -1, 20));

        jLabel51.setText("%");
        jPanel1.add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 360, -1, 20));
        jPanel1.add(txtid, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 420, 60, -1));

        btnfoto.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnfoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/foto.png"))); // NOI18N
        btnfoto.setText("Cargar");
        jPanel1.add(btnfoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 140, 100, -1));

        jTabbedPane1.addTab("Datos Personales", jPanel1);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel19.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel19.setText("Calle");
        jPanel2.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));
        jPanel2.add(txtcalle, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, 230, -1));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setText("No.");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 50, -1, -1));
        jPanel2.add(txtnum, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 50, 160, -1));

        jLabel20.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel20.setText("Colonia");
        jPanel2.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));
        jPanel2.add(txtcol, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, 230, -1));

        jLabel21.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel21.setText("C.P.");
        jPanel2.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 90, -1, -1));
        jPanel2.add(txtcp, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 90, 160, -1));

        jLabel22.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel22.setText("Municipio");
        jPanel2.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));
        jPanel2.add(txtmun, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, 230, -1));

        jLabel23.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel23.setText("Estado");
        jPanel2.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 130, -1, -1));
        jPanel2.add(txtest, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 130, 160, -1));

        jLabel42.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel42.setText("Domicilio");
        jPanel2.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));
        jPanel2.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 560, 10));

        jLabel46.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel46.setText("Documentación");
        jPanel2.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, -1, -1));
        jPanel2.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 560, 10));

        jCheckBox1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jCheckBox1.setText("Solicitud de Admisión para la Maestría");
        jPanel2.add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, -1, -1));

        jCheckBox2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jCheckBox2.setText("Acta de Nacimiento");
        jPanel2.add(jCheckBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, -1, -1));

        jCheckBox3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jCheckBox3.setText("Credencial de Elector");
        jPanel2.add(jCheckBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, -1, -1));

        jCheckBox4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jCheckBox4.setText("CURP");
        jPanel2.add(jCheckBox4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, -1, -1));

        jCheckBox5.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jCheckBox5.setText("Carta de Exposición de Motivos");
        jPanel2.add(jCheckBox5, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 210, -1, -1));

        jCheckBox6.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jCheckBox6.setText("Foto");
        jPanel2.add(jCheckBox6, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 240, -1, -1));

        jCheckBox7.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jCheckBox7.setText("Cedúla Federal");
        jPanel2.add(jCheckBox7, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 270, -1, -1));

        jCheckBox8.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jCheckBox8.setText("Título Profesional");
        jPanel2.add(jCheckBox8, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 300, -1, -1));

        jLabel47.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel47.setText("Observaciones");
        jPanel2.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, -1, -1));

        jScrollPane2.setViewportView(txtobs);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, 560, 70));

        jTabbedPane1.addTab("Domicilio - Documentación", jPanel2);

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel26.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel26.setText("Nombre de la Universidad");
        jPanel3.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        jLabel27.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel27.setText("Dirección de la Universidad");
        jPanel3.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        jLabel28.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel28.setText("Licenciatura");
        jPanel3.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, -1));
        jPanel3.add(txtnomuni, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 50, 350, -1));
        jPanel3.add(txtuniciu, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 80, 210, -1));
        jPanel3.add(txtuniest, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 80, 130, -1));

        jLabel29.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel29.setText("Ciudad");
        jPanel3.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 100, 210, -1));

        jLabel30.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel30.setText("Estado");
        jPanel3.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 100, 130, -1));
        jPanel3.add(txtlic, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 120, 350, -1));

        jLabel31.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel31.setText("Está Titulado");
        jPanel3.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, -1));

        titlic.add(rblicsi);
        rblicsi.setText("Si");
        jPanel3.add(rblicsi, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 150, -1, -1));

        titlic.add(rblicno);
        rblicno.setText("No");
        jPanel3.add(rblicno, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 150, -1, -1));

        jLabel32.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel32.setText("Otro, especifique");
        jPanel3.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, -1, -1));
        jPanel3.add(txtotro, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 180, 350, -1));
        jPanel3.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 560, 10));

        jLabel52.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel52.setText("Licenciatura");
        jPanel3.add(jLabel52, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        jTabbedPane1.addTab("Antecedentes Académicos", jPanel3);

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel33.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel33.setText("Seleccione el posgrado?");
        jPanel4.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        jLabel40.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel40.setText("Estudios realizados");
        jPanel4.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        jLabel41.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel41.setText("Nombre de la Universidad");
        jPanel4.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));
        jPanel4.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 560, 10));

        jLabel45.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel45.setText("¿Los concluyó?");
        jPanel4.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));
        jPanel4.add(txtpos, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 80, 350, -1));
        jPanel4.add(txtposuni, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 110, 350, -1));

        conluyomae.add(rbpossi);
        rbpossi.setText("Si");
        jPanel4.add(rbpossi, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 140, -1, -1));

        conluyomae.add(rbposno);
        rbposno.setText("No");
        jPanel4.add(rbposno, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 140, -1, -1));

        tituladomae.add(rbtitsi);
        rbtitsi.setText("Si");
        jPanel4.add(rbtitsi, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 140, -1, -1));

        tituladomae.add(rbtitno);
        rbtitno.setText("No");
        jPanel4.add(rbtitno, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 140, -1, -1));

        jLabel49.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel49.setText("Titulado");
        jPanel4.add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 140, -1, -1));

        jLabel54.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel54.setText("Posgrados");
        jPanel4.add(jLabel54, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        cmbpos.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        cmbpos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione una Opción", "Licenciatura", "Diplomado", "Maestria", "Doctorado" }));
        jPanel4.add(cmbpos, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 50, 160, -1));

        tblposgrado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane3.setViewportView(tblposgrado);

        jPanel4.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 210, 550, 190));

        btnagregar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnagregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/nuevo.png"))); // NOI18N
        btnagregar.setText("Agregar");
        btnagregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnagregarActionPerformed(evt);
            }
        });
        jPanel4.add(btnagregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 170, 120, -1));

        btnel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/eliminar.png"))); // NOI18N
        jPanel4.add(btnel, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 410, -1, -1));

        btned.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/editar.png"))); // NOI18N
        jPanel4.add(btned, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 410, -1, -1));

        jTabbedPane1.addTab("Estudios de Posgrado", jPanel4);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 580, 470));

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 0, 10, 530));

        jLabel24.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel24.setText("Buscar Alumnos");
        getContentPane().add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 20, -1, -1));
        getContentPane().add(txtbuscaralu, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 40, 390, -1));

        tblalumnos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tblalumnos.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jScrollPane1.setViewportView(tblalumnos);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 70, 390, 410));

        btnnuevo.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnnuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/nuevo.png"))); // NOI18N
        btnnuevo.setText("Nuevo");
        getContentPane().add(btnnuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 490, 120, -1));

        btnguardar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnguardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/guardar.png"))); // NOI18N
        btnguardar.setText("Guardar");
        getContentPane().add(btnguardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 490, 120, -1));

        btncancelar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btncancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cancelar.png"))); // NOI18N
        btncancelar.setText("Cancelar");
        getContentPane().add(btncancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 490, 120, -1));

        btneditar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btneditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/editar.png"))); // NOI18N
        btneditar.setText("Editar");
        btneditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneditarActionPerformed(evt);
            }
        });
        getContentPane().add(btneditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 490, 120, -1));

        btneliminar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btneliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/eliminar.png"))); // NOI18N
        btneliminar.setText("Eliminar");
        getContentPane().add(btneliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 490, 120, -1));

        btnsalir.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnsalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/salir.png"))); // NOI18N
        btnsalir.setText("Salir");
        btnsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalirActionPerformed(evt);
            }
        });
        getContentPane().add(btnsalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 490, 120, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btneditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneditarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btneditarActionPerformed

    private void btnsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalirActionPerformed
        
    }//GEN-LAST:event_btnsalirActionPerformed

    private void txtcurpFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtcurpFocusLost
        // TODO add your handling code here:
        String curp_alu = null;
        boolean sexo_alu;
        int edad_alu;
        curp_alu = txtcurp.getText();
        
        if(curp_alu.substring(10,11).equals("H")){
            cmbsexo.setSelectedIndex(0);
            sexo_alu=false;
        }else{
            cmbsexo.setSelectedIndex(1);
            sexo_alu=true;
        }
        
        txtfecnac.setText(curp_alu.substring(8,10)+"-"+curp_alu.substring(6,8)+"-"+"19"+curp_alu.substring(4,6));

        DateTimeFormatter fmt = DateTimeFormatter.ofPattern("dd-MM-yyyy");
        LocalDate fechaNac = LocalDate.parse(txtfecnac.getText(), fmt);
        LocalDate ahora = LocalDate.now();            
        Period periodo = Period.between(fechaNac, ahora);
        txtedad.setText(Integer.toString(periodo.getYears()));
        edad_alu = Integer.parseInt(txtedad.getText());
    }//GEN-LAST:event_txtcurpFocusLost

    private void lblfotoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblfotoMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_lblfotoMouseClicked

    private void btnagregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnagregarActionPerformed
        // TODO add your handling code here:
        
        
        
        
    }//GEN-LAST:event_btnagregarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.ButtonGroup Porcentaje;
    public javax.swing.JButton btnagregar;
    public javax.swing.JButton btncancelar;
    public javax.swing.JButton btned;
    public javax.swing.JButton btneditar;
    public javax.swing.JButton btnel;
    public javax.swing.JButton btneliminar;
    public javax.swing.JButton btnfoto;
    public javax.swing.JButton btnguardar;
    public javax.swing.JButton btnnuevo;
    public javax.swing.JButton btnsalir;
    public javax.swing.JComboBox<String> cmbpos;
    public javax.swing.JComboBox<String> cmbpro;
    public javax.swing.JComboBox<String> cmbsexo;
    public javax.swing.ButtonGroup concluyodoc;
    public javax.swing.ButtonGroup conluyodip;
    public javax.swing.ButtonGroup conluyomae;
    public javax.swing.JCheckBox jCheckBox1;
    public javax.swing.JCheckBox jCheckBox2;
    public javax.swing.JCheckBox jCheckBox3;
    public javax.swing.JCheckBox jCheckBox4;
    public javax.swing.JCheckBox jCheckBox5;
    public javax.swing.JCheckBox jCheckBox6;
    public javax.swing.JCheckBox jCheckBox7;
    public javax.swing.JCheckBox jCheckBox8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    public javax.swing.JLabel jLabel16;
    public javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    public javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    public javax.swing.JLabel jLabel50;
    public javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JTabbedPane jTabbedPane1;
    public javax.swing.JLabel lblfoto;
    public javax.swing.JRadioButton rblicno;
    public javax.swing.JRadioButton rblicsi;
    public javax.swing.JRadioButton rbpormix;
    public javax.swing.JRadioButton rbporper;
    public javax.swing.JRadioButton rbporpro;
    public javax.swing.JRadioButton rbposno;
    public javax.swing.JRadioButton rbpossi;
    public javax.swing.JRadioButton rbtitno;
    public javax.swing.JRadioButton rbtitsi;
    public javax.swing.JTable tblalumnos;
    public javax.swing.JTable tblposgrado;
    public javax.swing.ButtonGroup titlic;
    public javax.swing.ButtonGroup tituladodip;
    public javax.swing.ButtonGroup tituladodoc;
    public javax.swing.ButtonGroup tituladomae;
    public javax.swing.JTextField txtapmat;
    public javax.swing.JTextField txtappat;
    public javax.swing.JTextField txtbuscaralu;
    public javax.swing.JTextField txtcalle;
    public javax.swing.JTextField txtcel;
    public javax.swing.JTextField txtcol;
    public javax.swing.JTextField txtcp;
    public javax.swing.JTextField txtcurp;
    public javax.swing.JTextField txtedad;
    public javax.swing.JTextField txtemail;
    public javax.swing.JTextField txtest;
    public javax.swing.JTextField txtestciv;
    public javax.swing.JTextField txtfecnac;
    public javax.swing.JTextField txtfijo;
    public javax.swing.JTextField txtid;
    public javax.swing.JTextField txtlic;
    public javax.swing.JTextField txtmatricula;
    public javax.swing.JTextField txtmun;
    public javax.swing.JTextField txtnombre;
    public javax.swing.JTextField txtnomuni;
    public javax.swing.JTextField txtnum;
    public javax.swing.JTextPane txtobs;
    public javax.swing.JTextField txtotro;
    public javax.swing.JTextField txtporper;
    public javax.swing.JTextField txtporpro;
    public javax.swing.JTextField txtpos;
    public javax.swing.JTextField txtposuni;
    public javax.swing.JTextField txtuniciu;
    public javax.swing.JTextField txtuniest;
    // End of variables declaration//GEN-END:variables
}
